/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_obomprogramador_hog_HogComparator */

#ifndef _Included_com_obomprogramador_hog_HogComparator
#define _Included_com_obomprogramador_hog_HogComparator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_obomprogramador_hog_HogComparator
 * Method:    compareFaces
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_obomprogramador_hog_HogComparator_compareFaces
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
